### ISSUE TITLE
Investigate how we can implement beeping 

### ISSUE THREAD

**Issue by adit299** [adit299/android_interval_timer#10]
- We need to see how we can get the phone to produce a noise 
- We also want to see how the phone can vibrate as well 
- We need to investigate how the beeping mechanism can be notified when it is time for it to beep again

**Comment by AdamRust** [comment]
As discussed:
- Maybe it would nice to change the notifications so that it's different from all other default notifications
- It would be great to have some sort of distinctive representation of the timer on the lock screen
  - So instead of getting a normal notification, the user would hear a distinct sound and could then see the timer values persisted on the lock screen
- While the app is open, the user gets the normal beep and the number of intervals increases
  - It would also be cool to have some sort of cool visual cue to show the user that the interval just happened (like a screen flash or something)
